// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSa0KwrZdt9WNklZh_XkHwocgNJHBxNN8',
    appId: '1:535242589665:web:e9c09bbdc08425a694fea0',
    messagingSenderId: '535242589665',
    projectId: 'catalog-app-d2526',
    authDomain: 'catalog-app-d2526.firebaseapp.com',
    storageBucket: 'catalog-app-d2526.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKO0f2BjdrPQKAyukQI9RspsqYkzBhZcY',
    appId: '1:535242589665:android:442d1cfc45acf56f94fea0',
    messagingSenderId: '535242589665',
    projectId: 'catalog-app-d2526',
    storageBucket: 'catalog-app-d2526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP134Y8scGC8dx4E4GB3KT3sOfjrBf8Y4',
    appId: '1:535242589665:ios:5239b4af7c13643394fea0',
    messagingSenderId: '535242589665',
    projectId: 'catalog-app-d2526',
    storageBucket: 'catalog-app-d2526.firebasestorage.app',
    iosClientId: '535242589665-7u0ko0dpgv2vb1hgc8la70utdh8hm3et.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP134Y8scGC8dx4E4GB3KT3sOfjrBf8Y4',
    appId: '1:535242589665:ios:5239b4af7c13643394fea0',
    messagingSenderId: '535242589665',
    projectId: 'catalog-app-d2526',
    storageBucket: 'catalog-app-d2526.firebasestorage.app',
    iosClientId: '535242589665-7u0ko0dpgv2vb1hgc8la70utdh8hm3et.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSa0KwrZdt9WNklZh_XkHwocgNJHBxNN8',
    appId: '1:535242589665:web:07f8c28172b2ff5f94fea0',
    messagingSenderId: '535242589665',
    projectId: 'catalog-app-d2526',
    authDomain: 'catalog-app-d2526.firebaseapp.com',
    storageBucket: 'catalog-app-d2526.firebasestorage.app',
  );
}
