// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIhLKwGy-bamC_8pQrYqkJKhOUBvzjZUc',
    appId: '1:1030068585541:web:your_web_app_id',
    messagingSenderId: '1030068585541',
    projectId: 'fir-auth-b1b20',
    authDomain: 'fir-auth-b1b20.firebaseapp.com',
    storageBucket: 'fir-auth-b1b20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhLKwGy-bamC_8pQrYqkJKhOUBvzjZUc',
    appId: '1:1030068585541:android:40310a3eab9130b1048f2c',
    messagingSenderId: '1030068585541',
    projectId: 'fir-auth-b1b20',
    storageBucket: 'fir-auth-b1b20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIhLKwGy-bamC_8pQrYqkJKhOUBvzjZUc',
    appId: '1:1030068585541:ios:your_ios_app_id',
    messagingSenderId: '1030068585541',
    projectId: 'fir-auth-b1b20',
    storageBucket: 'fir-auth-b1b20.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIhLKwGy-bamC_8pQrYqkJKhOUBvzjZUc',
    appId: '1:1030068585541:ios:your_macos_app_id',
    messagingSenderId: '1030068585541',
    projectId: 'fir-auth-b1b20',
    storageBucket: 'fir-auth-b1b20.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIhLKwGy-bamC_8pQrYqkJKhOUBvzjZUc',
    appId: '1:1030068585541:web:your_windows_app_id',
    messagingSenderId: '1030068585541',
    projectId: 'fir-auth-b1b20',
    authDomain: 'fir-auth-b1b20.firebaseapp.com',
    storageBucket: 'fir-auth-b1b20.firebasestorage.app',
  );
}
